language: node_js
node_js:
  - "10"
script:
  - npm run lint
  - npm run type-check
  - npm run download-test-assets && npm run test
deploy:
  on:
    branch: release
  provider: npm
  email: ginpei@gmail.com
  api_key: $NPM_TOKEN
